/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;/**
 *
 * @author milesnecker
 */
public class BoardGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public BoardGUI() {
        initComponents();
        setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); //centers frame on screen
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spot1 = new javax.swing.JButton();
        spot7 = new javax.swing.JButton();
        spot2 = new javax.swing.JButton();
        spot4 = new javax.swing.JButton();
        spot8 = new javax.swing.JButton();
        spot3 = new javax.swing.JButton();
        spot5 = new javax.swing.JButton();
        spot6 = new javax.swing.JButton();
        spot9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        spot1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot1.setSize(new java.awt.Dimension(195, 195));
        spot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot1ActionPerformed(evt);
            }
        });

        spot7.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot7.setSize(new java.awt.Dimension(195, 195));
        spot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot7ActionPerformed(evt);
            }
        });

        spot2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot2ActionPerformed(evt);
            }
        });

        spot4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot4.setSize(new java.awt.Dimension(195, 195));
        spot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot4ActionPerformed(evt);
            }
        });

        spot8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot8ActionPerformed(evt);
            }
        });

        spot3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot3.setToolTipText("");
        spot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot3ActionPerformed(evt);
            }
        });

        spot5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot5ActionPerformed(evt);
            }
        });

        spot6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot6ActionPerformed(evt);
            }
        });

        spot9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        spot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spot9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spot1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spot2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spot3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spot7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spot4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spot6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spot9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spot1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spot6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spot9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spot7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot8ActionPerformed
        runTurn(spot8, 7);
    }//GEN-LAST:event_spot8ActionPerformed

    private void spot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot3ActionPerformed
        runTurn(spot3, 2);
    }//GEN-LAST:event_spot3ActionPerformed

    private void spot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot6ActionPerformed
        runTurn(spot6, 5);
    }//GEN-LAST:event_spot6ActionPerformed

    private void spot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot9ActionPerformed
        runTurn(spot9, 8);
    }//GEN-LAST:event_spot9ActionPerformed

    private void spot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot2ActionPerformed
        runTurn(spot2, 1);
    }//GEN-LAST:event_spot2ActionPerformed

    private void spot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot1ActionPerformed
        runTurn(spot1, 0);
    }//GEN-LAST:event_spot1ActionPerformed

    private void spot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot4ActionPerformed
        runTurn(spot4, 3);
    }//GEN-LAST:event_spot4ActionPerformed

    private void spot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot5ActionPerformed
        runTurn(spot5, 4);
    }//GEN-LAST:event_spot5ActionPerformed

    private void spot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spot7ActionPerformed
        runTurn(spot7, 6);
    }//GEN-LAST:event_spot7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGUI().setVisible(true);
            }
        });
    }
private void runTurn(JButton x, int loc) {
    x.setEnabled(false);
    if(Player.getTurn() == 1) {
        x.setText("X");
    }
    else {
        x.setText("O");
    }
    Board b = Board.getInstance();
    b.updateBoard(loc);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton spot1;
    private javax.swing.JButton spot2;
    private javax.swing.JButton spot3;
    private javax.swing.JButton spot4;
    private javax.swing.JButton spot5;
    private javax.swing.JButton spot6;
    private javax.swing.JButton spot7;
    private javax.swing.JButton spot8;
    private javax.swing.JButton spot9;
    // End of variables declaration//GEN-END:variables
}